const InitialValues = {
  bannersoundMute: false,
  popularMovies: [],
  nowPlayingMovie: [],
  upComingMovie: [],
  genreMovie: [],
  animatedMovie: [],
  comedyMovie: [],
  actionMovies: [],
  adventuresMovie: [],
  crimeMovie: [],
  documentaryMovie: [],
  dramaMovie: [],
  familyMovie: [],
  fantasyMovi: [],
  horrorMovi: [],
  musicMovi: [],
  romanceMovie: [],
  scienceMovie: [],
  tvMovie: [],
  thrillerMovie: [],
  warMovie: [],
  westernMovie: [],
  topRated: [],
  movieId: null,
  randomeIdx: 1,
};

export { InitialValues };
